// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class SpotImage
    {
        public int ImageId { get; set; }
        public int? SpotId { get; set; }
        public string ImageTitle { get; set; }
        public string ImagePath { get; set; }
    }
}